parameters:
    ikuzo_sylius_mondial_relay.api.wdsl: 'https://api.mondialrelay.com/Web_Services.asmx?WSDL'

services:
  ikuzo_sylius_mondial_relay.form.type.mondial_relay_shipping_gateway:
    class: Ikuzo\SyliusMondialRelayPlugin\Form\Type\MondialRelayShippingGatewayType
    tags:
      - { name: bitbag.shipping_gateway_configuration_type, type: "mondial_relay", label: Mondial Relay }

  ikuzo_sylius_mondial_relay.provider.mondial_relay:
    class: Ikuzo\SyliusMondialRelayPlugin\Provider\MondialRelayProvider
    arguments:
      - '@ikuzo_sylius_mondial_relay.mondial_relay.api_client'
      - '@setono_sylius_pickup_point.factory.pickup_point'
    tags:
      - { name: 'setono_sylius_pickup_point.provider', code: 'mondial_relay', label: "ikuzo_sylius_mondial_relay.name" }

  ikuzo_sylius_mondial_relay.mondial_relay.api_client:
    class: Ikuzo\SyliusMondialRelayPlugin\MondialRelay\ApiClient
    arguments:
      - '%ikuzo_sylius_mondial_relay.api.wdsl%'
      - "@bitbag.repository.shipping_gateway"

  ikuzo_sylius_mondial_relay.event_listener.mondial_relay_shipping_export:
    class: Ikuzo\SyliusMondialRelayPlugin\EventListener\MondialRelayShippingExportEventListener
    arguments:
        - '@session'
        - '@filesystem'
        - '@bitbag.manager.shipping_export'
        - '%bitbag.shipping_labels_path%'
        - '@ikuzo_sylius_mondial_relay.mondial_relay.api_client'
    tags:
        - { name: kernel.event_listener, event: 'bitbag.shipping_export.export_shipment', method: exportShipment }
